FROM node:20 AS BUILDER

WORKDIR /app

COPY package.json package-lock.json ./
COPY src ./src

RUN ls

RUN npm ci
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:20 AS RELEASE

COPY  --from=BUILDER /app/dist/lambda.js ${LAMBDA_TASK_ROOT}

CMD [ "lambda.handler" ]